defaultPlacement: end
fieldLayouts:
  27c72910-179e-4a2e-a075-8034d8e4559e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 484ee798-4ae5-48fa-9d8b-f5a3bcab22fe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 96bb1d3d-4098-4112-9dc3-dbffbe908c62 # Tour Preview
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4b402ce-f743-491d-85f2-50d4740c22bc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a59e71ad-563d-4310-9781-643f3946d062
        userCondition: null
handle: tours
name: Tours
siteSettings:
  2c2e1c6a-eb4d-44f1-9a43-8d79b326f354: # ES
    hasUrls: true
    template: null
    uriFormat: 'tours/{slug}'
  547128fa-4529-4483-9968-66425996b69f: # EN
    hasUrls: true
    template: null
    uriFormat: 'tours/{slug}'
structure:
  maxLevels: null
  uid: e15eab9e-edd4-433c-a835-b45264b5a10f
