field: 9f7b6402-ce3b-4a99-9180-c0c6c3915642 # flexible
fieldLayouts:
  22bf4637-643b-40a7-abf2-8a011b346b1a:
    tabs:
      -
        elements:
          -
            fieldUid: 1345707a-2b07-4664-b8d2-25fcb9241212 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1345707a-2b07-4664-b8d2-25fcb9241212: # Content
    columnSuffix: vmlbdzgn
    contentColumnType: text
    fieldGroup: null
    handle: slideContent
    instructions: ''
    name: Content
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: funFactSlide
name: 'Fun Fact Slide'
sortOrder: 3
