field: 9f7b6402-ce3b-4a99-9180-c0c6c3915642 # flexible
fieldLayouts:
  125e77e9-6ae3-415b-ae26-5301dfcdf27b:
    tabs:
      -
        elements:
          -
            fieldUid: c5e2a1ff-7d99-4956-8b74-c79601fad6fe # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 433dd9ce-77cb-4942-8b4d-8e347439bc61 # Sub Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9f3fe24e-520b-44fc-97f5-fa9a2d2622b0 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9f3fe24e-520b-44fc-97f5-fa9a2d2622b0: # Content
    columnSuffix: ghgyiixf
    contentColumnType: text
    fieldGroup: null
    handle: slideContent
    instructions: ''
    name: Content
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  433dd9ce-77cb-4942-8b4d-8e347439bc61: # Sub Title
    columnSuffix: fsoshbeu
    contentColumnType: text
    fieldGroup: null
    handle: subTitle
    instructions: ''
    name: 'Sub Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  c5e2a1ff-7d99-4956-8b74-c79601fad6fe: # Title
    columnSuffix: cujmvetr
    contentColumnType: text
    fieldGroup: null
    handle: slideTitle
    instructions: ''
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: imageSlide
name: 'Default Slide'
sortOrder: 2
