field: 9f7b6402-ce3b-4a99-9180-c0c6c3915642 # flexible
fieldLayouts:
  0f1c2dbe-d0b5-4ff7-9474-d07717911191:
    tabs:
      -
        elements:
          -
            fieldUid: c5bc0051-46f3-4ac7-bb8a-a7b808c4b0a7 # Thumbnail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 20c31add-4c8c-4c9e-a6dc-4ccac3ecfe35 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 45e9d096-0ab6-4324-af5e-61a1be9cff83 # Sub Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4e3020e0-9db8-4f8c-8e2e-8884ac2a1a5d # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4e3020e0-9db8-4f8c-8e2e-8884ac2a1a5d: # Content
    columnSuffix: vpprjebi
    contentColumnType: text
    fieldGroup: null
    handle: slideContent
    instructions: ''
    name: Content
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  20c31add-4c8c-4c9e-a6dc-4ccac3ecfe35: # Title
    columnSuffix: znpxpszh
    contentColumnType: text
    fieldGroup: null
    handle: slideTitle
    instructions: ''
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  45e9d096-0ab6-4324-af5e-61a1be9cff83: # Sub Title
    columnSuffix: mhcnskqq
    contentColumnType: text
    fieldGroup: null
    handle: subTitle
    instructions: ''
    name: 'Sub Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c5bc0051-46f3-4ac7-bb8a-a7b808c4b0a7: # Thumbnail
    columnSuffix: vayzwtes
    contentColumnType: boolean
    fieldGroup: null
    handle: thumbnail
    instructions: ''
    name: Thumbnail
    searchable: false
    settings:
      default: false
      offLabel: 'Don''t use thumbnail'
      onLabel: 'Use thumbnail'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: introSlide
name: 'Intro Slide'
sortOrder: 2
