fieldLayouts:
  5bf4659c-c943-43d1-b8f5-f61a4e33ea93:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: __blank__
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 95f97cad-6bdb-4a62-9eed-2fd771cdb49f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7db205b7-a548-42f1-8c26-416ec51cf3fa # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f933963-795b-41a1-a1d6-7e42185ea3a8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3b6e9b3e-5e6d-444a-8182-9177c9badd8a
        userCondition: null
handle: about
hasTitleField: false
name: About
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
