color: null
description: null
fieldLayouts:
  5bf4659c-c943-43d1-b8f5-f61a4e33ea93:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-19T17:48:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 33ce6f85-e595-4035-b5ff-9d13639d4f22
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-13T18:20:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7db205b7-a548-42f1-8c26-416ec51cf3fa # Text
            handle: eyebrowText
            includeInCards: false
            instructions: null
            label: 'Eyebrow Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f933963-795b-41a1-a1d6-7e42185ea3a8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T17:50:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7db205b7-a548-42f1-8c26-416ec51cf3fa # Text
            handle: headerTitle
            includeInCards: false
            instructions: null
            label: 'Header Title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05128983-fc10-4b98-a548-a5d43b90962c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-13T18:23:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7db205b7-a548-42f1-8c26-416ec51cf3fa # Text
            handle: headerBody
            includeInCards: false
            instructions: null
            label: 'Header Body'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07e03580-c9c9-41bb-ae06-599b2a7dc972
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T19:55:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7db205b7-a548-42f1-8c26-416ec51cf3fa # Text
            handle: introBody
            includeInCards: false
            instructions: null
            label: 'Intro Body'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1bddbe20-763f-46e1-b60d-962510894fa0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T19:55:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8dcbb92-c170-4e0e-831b-d068fbd2f9b6 # About Image
            handle: introImage
            includeInCards: false
            instructions: null
            label: 'Intro Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8dc6419-c614-41ab-b783-179eafb980a7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T19:43:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7db205b7-a548-42f1-8c26-416ec51cf3fa # Text
            handle: responsiveBody
            includeInCards: false
            instructions: null
            label: 'Responsive Body'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98568ee7-81cf-40ed-9cdc-2cfb19ae6ddf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T19:43:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7db205b7-a548-42f1-8c26-416ec51cf3fa # Text
            handle: lowSettingLabel
            includeInCards: false
            instructions: null
            label: 'Low Setting Label'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3bdb326b-c7ee-4387-b432-e353e3971772
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T19:43:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7db205b7-a548-42f1-8c26-416ec51cf3fa # Text
            handle: lowSettingCount
            includeInCards: false
            instructions: null
            label: 'Low Setting Count'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4a37de4-f067-4d16-81e4-90cd14b42da6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T19:43:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8dcbb92-c170-4e0e-831b-d068fbd2f9b6 # About Image
            handle: lowSettingImages
            includeInCards: false
            instructions: null
            label: 'Low Setting Images'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0b98b72-062d-4f84-96ef-9a3a6cb28d59
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T19:48:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7db205b7-a548-42f1-8c26-416ec51cf3fa # Text
            handle: mediumSettingLabel
            includeInCards: false
            instructions: null
            label: 'Medium Setting Label'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 909edfdc-abd3-4ef3-92ab-b1d2df715b8f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T19:48:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7db205b7-a548-42f1-8c26-416ec51cf3fa # Text
            handle: mediumSettingCount
            includeInCards: false
            instructions: null
            label: 'Medium Setting Count'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b4cb3c2-13e2-4ccb-bef0-03fe7efc3a92
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T19:48:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8dcbb92-c170-4e0e-831b-d068fbd2f9b6 # About Image
            handle: mediumSettingImages
            includeInCards: false
            instructions: null
            label: 'Medium Setting Images'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b3c5436-6f07-49e5-ac5f-e6f621a12435
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T19:48:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7db205b7-a548-42f1-8c26-416ec51cf3fa # Text
            handle: highSettingLabel
            includeInCards: false
            instructions: null
            label: 'High Setting Label'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 207d0ed9-1ad4-4161-976a-f8d1fd850cca
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T19:48:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7db205b7-a548-42f1-8c26-416ec51cf3fa # Text
            handle: highSettingCount
            includeInCards: false
            instructions: null
            label: 'High Setting Count'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37f8c832-d6f6-4249-9766-b3b7040a8996
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T19:48:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8dcbb92-c170-4e0e-831b-d068fbd2f9b6 # About Image
            handle: highSettingImages
            includeInCards: false
            instructions: null
            label: 'High Setting Images'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e504b6be-473c-48bc-bfa4-136a03327024
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T19:48:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7db205b7-a548-42f1-8c26-416ec51cf3fa # Text
            handle: ultraSettingLabel
            includeInCards: false
            instructions: null
            label: 'Ultra Setting Label'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11d6fab4-e6c9-4c11-8c8f-a42de4c17158
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T19:48:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7db205b7-a548-42f1-8c26-416ec51cf3fa # Text
            handle: ultraSettingCount
            includeInCards: false
            instructions: null
            label: 'Ultra Setting Count'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39dc1cbb-fd10-4233-b111-2c161cc4e956
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T19:48:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8dcbb92-c170-4e0e-831b-d068fbd2f9b6 # About Image
            handle: ultraSettingImages
            includeInCards: false
            instructions: null
            label: 'Ultra Setting Images'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0cd568af-5f60-4990-a8e2-e29a217c0904
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T19:53:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7db205b7-a548-42f1-8c26-416ec51cf3fa # Text
            handle: observatoryBody
            includeInCards: false
            instructions: null
            label: 'Observatory Body'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a40d115a-629e-45aa-84f0-9c8a4d959e96
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T19:53:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8dcbb92-c170-4e0e-831b-d068fbd2f9b6 # About Image
            handle: observatoryImage
            includeInCards: false
            instructions: null
            label: 'Observatory Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a18ff355-a8ab-4ff0-94f2-69901a1e1eda
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T19:53:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7db205b7-a548-42f1-8c26-416ec51cf3fa # Text
            handle: footerText
            includeInCards: false
            instructions: null
            label: 'Footer Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e0b86de-1f1f-4af2-99b7-73c7fa2504ed
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T19:53:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8dcbb92-c170-4e0e-831b-d068fbd2f9b6 # About Image
            handle: footerImage
            includeInCards: false
            instructions: null
            label: 'Footer Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e149956a-f569-45af-9ba5-fec606daf599
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T19:53:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7db205b7-a548-42f1-8c26-416ec51cf3fa # Text
            handle: creditsText
            includeInCards: false
            instructions: null
            label: Credits
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9801412-0617-4e3c-834e-83cc8df099c4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3b6e9b3e-5e6d-444a-8182-9177c9badd8a
        userCondition: null
handle: about
hasTitleField: true
icon: null
name: About
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: none
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
