fieldLayouts:
  d93895fc-2854-4e6f-bb32-eb0b2b6cf0ed:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 90b39177-0024-423b-8714-7ddd0550f6f1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b49a6e91-b631-4ade-92cc-8c3e3f6db788 # Customize Orbits Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4220c355-f88f-4ede-9a73-3e5bb0749498
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7559fb47-f35b-436d-aceb-300a233317b8 # Customize Orbits Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49a9196d-a5c6-48bf-a224-d95e6812ae15
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 252e8a20-8465-4a3b-905d-f1e6b5edbb49
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8fff3c50-28ba-4af7-8166-e3d82a23ae26 # SEO Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbc195c6-71e2-42b5-8973-3f85b4267e97
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: acbea415-ee80-409c-90e2-90ac546820a6 # SEO Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41594223-052e-4431-9a95-696b38205a33
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 294114c2-b0a2-4c1e-971b-f6ab75b78e88 # SEO Share Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b477d0e0-086e-4690-b842-17522676ad61
            userCondition: null
            warning: null
            width: 100
        name: Seo
        uid: 7573dae6-e544-455e-a733-eeae7394fe8f
        userCondition: null
handle: customizeOrbits
hasTitleField: false
name: 'Customize Orbits'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
