color: null
description: null
fieldLayouts:
  d93895fc-2854-4e6f-bb32-eb0b2b6cf0ed:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6613c609-c881-4920-8b0a-d9d5cf1b1954
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: b49a6e91-b631-4ade-92cc-8c3e3f6db788 # Customize Orbits Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a34d895e-8e39-4e66-874b-3237ad6c99e6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 7559fb47-f35b-436d-aceb-300a233317b8 # Customize Orbits Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b459f00-c0a4-4bff-919f-b167c49cc983
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5394ec5a-fb0b-4141-9590-5e2b941827a2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 8fff3c50-28ba-4af7-8166-e3d82a23ae26 # SEO Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c8c4fc5-6914-4827-98dc-45c53b04001d
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: acbea415-ee80-409c-90e2-90ac546820a6 # SEO Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b426cbaf-97c9-4884-bd7e-ee5b07d639ed
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 294114c2-b0a2-4c1e-971b-f6ab75b78e88 # SEO Share Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 104f8bba-ab48-4f43-af43-1bbe6dc0ed6d
            userCondition: null
            warning: null
            width: 100
        name: Seo
        uid: 0420a075-2edb-454d-9662-3f419b8bc232
        userCondition: null
handle: customizeOrbits
hasTitleField: false
icon: null
name: 'Customize Orbits'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
