fieldLayouts:
  932dc7e8-1c60-4383-9fd0-703d43134cd2:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 3182a473-667d-439f-9cf2-b545be5c23d3 # Element ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 53d8b6b6-280e-4d4a-adc1-2c3efcb4bd0a # Element Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 08df75ba-ecc2-470d-84c2-f004b1d30739 # Preview
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Reference
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 29b451f0-26dc-4eae-af12-3041039632b0 # Diameter
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Overview
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 7db205b7-a548-42f1-8c26-416ec51cf3fa # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Context Information'
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 259c53da-eb2c-4ed5-9688-265402477b30 # View In Skyviewer Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Detailed Data'
        sortOrder: 4
handle: default
hasTitleField: true
name: Default
section: 59e08766-55d3-4cb0-8b02-b406b1ea45d8 # Solar system Elements
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
