fieldLayouts:
  ec58d409-2cc8-4a47-94f9-774ebe51dc73:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 345d14fb-3b49-4821-94d9-0d3653a65695
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 37b1d17c-d8d5-45f3-9c15-14ef09b62add # Tour Picker
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68d90301-11f4-4221-b03b-be75793b06e6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 96bb1d3d-4098-4112-9dc3-dbffbe908c62 # Tour Preview
            instructions: null
            label: Preview
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9181823c-d18b-4bb8-bf39-d4d740a13645
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e7f9aec-f2f0-4d0d-bd27-ab2662ab3e08 # Duration
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4de7be11-1395-40a6-8eb1-c1e1fe4a5b5d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ea7cafd8-b2d5-4ffb-b9fb-9a617eef9dfb # Complexity
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf3cc666-43ab-4472-9278-ba56e5ae0f8f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9f7b6402-ce3b-4a99-9180-c0c6c3915642 # flexible
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 064d96e0-c9e3-48bc-b13f-c6121d610d10
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3358a9fd-a578-4413-bf31-a8862ba43109
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8fff3c50-28ba-4af7-8166-e3d82a23ae26 # SEO Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 304e1a9e-415b-472a-966c-7120bf6eedc2
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: acbea415-ee80-409c-90e2-90ac546820a6 # SEO Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b0c9a07-48a6-493c-b192-c7d7de1535da
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 294114c2-b0a2-4c1e-971b-f6ab75b78e88 # SEO Share Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6975839-579f-450b-84a7-525c352c5275
            userCondition: null
            warning: null
            width: 100
        name: Seo
        uid: 0ca83f36-e077-4635-a959-7a0dbf32e844
        userCondition: null
handle: default
hasTitleField: true
name: Default
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
