color: null
description: null
fieldLayouts:
  22bf4637-643b-40a7-abf2-8a011b346b1a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 1345707a-2b07-4664-b8d2-25fcb9241212
            handle: slideContent
            includeInCards: true
            instructions: null
            label: Content
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fecc8319-43b2-4ee9-a92e-4096aab4dde7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a12d9c95-d272-4fc4-9e17-466f2154f908
        userCondition: null
handle: funFactSlide
hasTitleField: false
icon: null
name: 'Fun Fact Slide'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
