color: null
description: null
fieldLayouts:
  bd11cb91-00ac-4b88-b9b4-b660be992d98:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-11T18:07:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 37128011-dbda-4360-85b0-a8668f7674d7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-11T20:40:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5e48c132-d42b-4192-8aa6-40e239f6889e # Data File Quality
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce8666e9-a5f2-4921-a8dc-ca6000f784e4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-11T18:19:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7970cd65-7a96-418a-8581-d6df4e039e6d # Plain Text
            handle: dataFileUrl
            includeInCards: false
            instructions: null
            label: 'MPC Data File URL'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6329158f-cbf4-4c18-9a7d-e2b7e412e97e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 48d47f53-00b6-46f3-9f07-176c3fdd2fa2
        userCondition: null
handle: mpcDataFiles
hasTitleField: true
icon: file-chart-column
name: 'MPC Data Files'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
