fieldLayouts:
  8496a8ac-bbb0-44c1-a0e5-0f3605515016:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 392f69f0-0536-478c-a572-faee0ecac2cc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8fff3c50-28ba-4af7-8166-e3d82a23ae26 # SEO Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 042aa0f4-f3de-4113-b2d7-67eb8d29033b
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: acbea415-ee80-409c-90e2-90ac546820a6 # SEO Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dda6419b-7747-4362-ae5e-cf9d434186ca
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 294114c2-b0a2-4c1e-971b-f6ab75b78e88 # SEO Share Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: afb30e4d-8eab-4a92-8901-342c96ab5557
            userCondition: null
            warning: null
            width: 100
        name: Seo
        uid: f838baa4-a44b-4e5b-828b-252137eb6186
        userCondition: null
handle: orbitViewer
hasTitleField: false
name: 'Orbit Viewer'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
