fieldLayouts:
  8496a8ac-bbb0-44c1-a0e5-0f3605515016:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b9d5070d-4512-4c4a-acb6-4ff64d8e70cf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8fff3c50-28ba-4af7-8166-e3d82a23ae26 # SEO Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11924472-301c-42d6-8850-815affb8e445
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: acbea415-ee80-409c-90e2-90ac546820a6 # SEO Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73bb553c-e33b-43ef-8036-1ff54e5a73da
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 294114c2-b0a2-4c1e-971b-f6ab75b78e88 # SEO Share Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bcd0a971-3d9c-4d40-bd72-6dac30f79398
            userCondition: null
            warning: null
            width: 100
        name: Seo
        uid: 2c1be1fe-316f-46a2-aa58-897c4ed16821
        userCondition: null
handle: orbitViewer
hasTitleField: false
name: 'Orbit Viewer'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
