fieldLayouts:
  8496a8ac-bbb0-44c1-a0e5-0f3605515016:
    tabs:
      -
        elements:
          -
            fieldUid: 8fff3c50-28ba-4af7-8166-e3d82a23ae26 # SEO Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: acbea415-ee80-409c-90e2-90ac546820a6 # SEO Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
          -
            fieldUid: 294114c2-b0a2-4c1e-971b-f6ab75b78e88 # SEO Share Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Seo
        sortOrder: 1
handle: orbitViewer
hasTitleField: false
name: 'Orbit Viewer'
section: 00d2f19f-361b-48e1-bcad-9af116c709c2 # Orbit Viewer
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
