fieldLayouts:
  8496a8ac-bbb0-44c1-a0e5-0f3605515016:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e1ce1aef-589e-4465-ba36-e391c6e678b9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8fff3c50-28ba-4af7-8166-e3d82a23ae26 # SEO Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6db5a099-b68e-4a3a-ab23-dbe7e49659bc
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: acbea415-ee80-409c-90e2-90ac546820a6 # SEO Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b022f3ff-6323-4556-bf75-aa996326dc83
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 294114c2-b0a2-4c1e-971b-f6ab75b78e88 # SEO Share Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5bdf0f4-45d3-40e4-b538-21193d897cdb
            userCondition: null
            warning: null
            width: 100
        name: Seo
        uid: 0e0e20e1-4bdd-427f-903a-e5de860d2a29
        userCondition: null
handle: orbitViewer
hasTitleField: false
name: 'Orbit Viewer'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
