color: null
description: null
fieldLayouts:
  60511076-e137-4265-860d-d19bd833234a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: d77e6076-0548-4254-b697-8ffa9980271b # flexible - Share Slide - Title
            handle: slideTitle
            includeInCards: true
            instructions: null
            label: Title
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2852c55a-902b-434b-b191-949e5cf79dfd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 3cc93b5a-26a7-43b2-98d9-1d346f30440b # flexible - Share Slide - Text
            handle: null
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 841cb5de-d7e0-43c6-b0ad-902959d1a9be
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: ac760e25-4731-4206-b6a8-bc36fbf95448 # flexible - Share Slide - Links Title
            handle: null
            includeInCards: false
            instructions: null
            label: 'Links Title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2593ce4-4ffe-467b-8634-68751c400ed1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 19012886-9bc8-45c8-98ca-619268a128d4 # flexible - Share Slide - Link 1
            handle: null
            includeInCards: false
            instructions: null
            label: 'Link 1'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34534f55-34be-4668-ae7c-d26330f447ce
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: ccafd7ca-3768-4e9f-92c6-56ed30825dd3 # flexible - Share Slide - Link 1 Text
            handle: null
            includeInCards: false
            instructions: null
            label: 'Link 1 Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25a1c8cf-d7f7-41e3-8291-95c0498011cc
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 510835eb-8d26-4284-abbd-01750b50e6e0 # flexible - Share Slide - Link 2
            handle: null
            includeInCards: false
            instructions: null
            label: 'Link 2'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 022fb8b6-36b0-40cc-8453-cb6d8d1b1137
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 5ec16768-675f-4821-9d5c-bdda6be16ddf # flexible - Share Slide - Link 2 Text
            handle: null
            includeInCards: false
            instructions: null
            label: 'Link 2 Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47a0aebe-d927-446d-8960-3b5a0fbb6d55
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: a320b687-d7a3-4cba-9a9f-f696c52c859c # flexible - Share Slide - Link 3
            handle: null
            includeInCards: false
            instructions: null
            label: 'Link 3'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c504cf71-63b7-4987-a9ce-8c2a59f1edcb
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: b8a1185f-57c4-4db0-a5c8-fab494cbef2d # flexible - Share Slide - Link 3 Text
            handle: null
            includeInCards: false
            instructions: null
            label: 'Link 3 Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0c199c1-c5d3-4ff7-a95a-a7b1bdbf9621
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 18324a33-d4f9-424d-b03a-c1e74f127122 # flexible - Share Slide - Link 4
            handle: null
            includeInCards: false
            instructions: null
            label: 'Link 4'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf6d3e21-3a42-4dbf-a1c9-c0ea3460c440
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 3d8ca907-3314-4e70-8195-610c75f3ef68 # flexible - Share Slide - Link 4 Text
            handle: null
            includeInCards: false
            instructions: null
            label: 'Link 4 Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ae39cb8-c8e8-4bc5-a2a9-692a80ececa0
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 17cb5727-3b29-4e3b-b7a0-3413ec7915f3
        userCondition: null
handle: shareSlide
hasTitleField: false
icon: null
name: 'Share Slide'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
