fieldLayouts:
  be794d37-5f99-4adf-af45-94f8a1d18362:
    tabs:
      -
        elements:
          -
            fieldUid: a5d58b4b-7ea2-4626-a2aa-4ab4b6e215c7 # Edit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 31e87e52-ecde-4fb4-b8d4-0bc17ddba4f7 # Apply
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 22edc2f0-4993-43c9-b35e-319f2deaf730 # Cancel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: b9a006e5-24a8-4ff3-acc9-e8457785163c # Reset
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Buttons
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 6b607634-7580-4f3a-9958-c7883897e1c0 # Near
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 6bfb86e1-cb0b-4784-8066-ab45ba52b3e2 # Far
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 6fa60013-56a6-4e61-8935-871e6cca0536 # Past
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 889fb8bb-51de-48ae-9f65-5df124aec8a7 # Future
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 6d856af2-d9d3-4725-a80d-dd0022c0c4b1 # Filter
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Strings
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 3c3371e1-1c92-4e4b-acad-5748d1ba9713 # Search Placeholder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: aedb4cc7-8e36-49f3-affd-eeecf690a5a6 # Show Random Object Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Search
        sortOrder: 3
handle: commonStrings
name: 'Common Strings'
sortOrder: 4
