fieldLayouts:
  f281aa4f-cbec-4907-a51d-9eba5f68bfba:
    tabs:
      -
        elements:
          -
            fieldUid: 57594c75-791b-46eb-9ba1-6b174ab4872a # DatePicker Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fadf9022-eca1-4363-80a6-f415eb299321 # DatePicker Go to Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Texts
        sortOrder: 1
handle: datepickerPanel
name: 'DatePicker Panel'
sortOrder: 6
