fieldLayouts:
  287314c0-b557-40d3-83b5-84637048f850:
    tabs:
      -
        elements:
          -
            fieldUid: 0a0fd614-6a5f-41e9-9dee-84b661323f31 # Menu Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fc53e1f0-3f64-42f2-a532-79469490caaa # Menu Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f5b01309-7a7a-4ae7-898c-eaea681e11a5 # Section 1 Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 255abff9-94b4-4966-b0e9-f4a57d309ef0 # Section 2 Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Texts
        sortOrder: 1
handle: mainMenu
name: 'Main Menu'
sortOrder: 3
