dateModified: 1661344377
email:
  fromEmail: $EMAIL_FROM_ADDRESS
  fromName: $EMAIL_SENDER_NAME
  replyToEmail: $EMAIL_REPLY_TO_ADDRESS
  template: $EMAIL_HTML_EMAIL_TEMPLATE
  transportSettings:
    encryptionMethod: tls
    host: $EMAIL_SMTP_HOST_NAME
    password: $EMAIL_SMTP_PASSWORD
    port: $EMAIL_SMTP_PORT
    timeout: '10'
    useAuthentication: '1'
    username: $EMAIL_SMTP_USERNAME
  transportType: craft\mail\transportadapters\Smtp
meta:
  __names__:
    0aebf207-b8e4-46e9-9148-b9075e55a0a9: 'Landing Left Button Text' # Landing Left Button Text
    0eccfbd3-ee20-4548-bc48-01195998260d: 'Customize Orbits' # Customize Orbits
    0f48338c-1c16-4600-9230-68bacb7c21e3: Text # Text
    1a35bfab-6a39-4c03-b273-2d5e3151c335: 'Rubin Telescope Education and Public Outreach' # Rubin Telescope Education and Public Outreach
    1c3041a4-1be7-450a-9165-19dd3458cc69: 'Customize Orbits Button' # Customize Orbits Button
    1e0c12ac-5dd7-4ed2-8cda-3801130b11e1: 'Gallery Item' # Gallery Item
    1ed94e58-7078-46fb-b590-0692fbdf9c20: 'Common Name' # Common Name
    1f8a9fe3-0e8c-4e3f-b6ce-0e1421fe0fbb: 'Landing Center Title' # Landing Center Title
    2c2e1c6a-eb4d-44f1-9a43-8d79b326f354: ES # ES
    2f6b435a-5a6c-4f32-b8b5-4aae301d1738: 'Customize Orbits' # Customize Orbits
    3c4d26f3-4aa2-48fd-8dd8-400929f9210e: Tours # Tours
    3cbe4fda-03b6-4891-b0ac-892db5b17bb8: Landing # Landing
    3df02181-c6a1-4e72-98fb-f91def384206: Entry # Entry
    4b94ba3d-060c-4a09-b2dc-c519a4c83709: 'Cell Content' # Cell Content
    4e3020e0-9db8-4f8c-8e2e-8884ac2a1a5d: Content # Content
    4fe339ec-7579-46f4-a362-df6ee8de4b3c: 'Public Schema' # Public Schema
    5ca18cb3-5a7b-4764-9e18-fc24b4cecc14: Flag # Flag
    06f925f8-298e-494b-bff7-6fe8024c0859: Frontend # Frontend
    8ccd6c1c-8e9b-44e8-93a9-f62589fb4819: 'Site Information' # Site Information
    8e3c01b6-fbcb-466f-9335-925f168e8b40: 'Coming Soon' # Coming Soon
    8fff3c50-28ba-4af7-8166-e3d82a23ae26: Title # Title
    9ad13bcd-637a-4757-9968-cdcc02cfd478: 'Table Row' # Table Row
    9ad945a2-a807-403c-aec6-ef28c7849b73: 'Landing Logo' # Landing Logo
    9c14ac7e-c466-4c2d-a2fd-e19a68fc706d: Teaser # Teaser
    9f3fe24e-520b-44fc-97f5-fa9a2d2622b0: Content # Content
    9f7b6402-ce3b-4a99-9180-c0c6c3915642: flexible # flexible
    16e8811b-6d9d-44e1-83b2-16c02e1dcd5a: 'Landing Version' # Landing Version
    20c31add-4c8c-4c9e-a6dc-4ccac3ecfe35: Title # Title
    37b1d17c-d8d5-45f3-9c15-14ef09b62add: 'Tour Picker' # Tour Picker
    45e9d096-0ab6-4324-af5e-61a1be9cff83: 'Sub Title' # Sub Title
    53d8b6b6-280e-4d4a-adc1-2c3efcb4bd0a: 'Element Category' # Element Category
    56f784c1-2182-4a9a-9e20-2e30e7b4a2bd: 'Solar system Elements' # Solar system Elements
    59e08766-55d3-4cb0-8b02-b406b1ea45d8: 'Solar system Elements' # Solar system Elements
    68ce46bb-bb2f-4e55-8009-fe56a7d4493b: Header # Header
    70ff59dd-8280-4bea-bef6-cfdf9ea4f0c2: 'Sort Options' # Sort Options
    95b97a67-eccb-4910-b0e8-77f5860058b4: Link # Link
    380c1cbe-884e-421b-9e31-1f0dfc81e15f: 'Cell Width' # Cell Width
    433dd9ce-77cb-4942-8b4d-8e347439bc61: 'Sub Title' # Sub Title
    522bc2d7-fcc3-4817-a986-5c860e53351c: 'Internal Entry' # Internal Entry
    907d717b-d9ff-4449-abbf-7c7f5823851b: 'Guided Experiences Page' # Guided Experiences Page
    0928ff1a-513d-41e0-acc1-606d93988618: 'Search Filters' # Search Filters
    966a6b65-ca53-48a8-89dc-74983cd624ef: Title # Title
    991c5031-3b97-45d8-8829-c8e0c79537a9: 'Row Title' # Row Title
    2755abe1-7dd5-428c-a6bb-30d2bd59a362: Link # Link
    3182a473-667d-439f-9cf2-b545be5c23d3: Fulldesignation # Fulldesignation
    3400f929-2ff0-47da-8c15-40bce8b6cebf: 'Customize Orbits' # Customize Orbits
    4294fb85-8029-437c-a2e5-76bcd1a79ef1: Asset # Asset
    5075e912-4aa1-4ce4-96b2-8868358b51e3: Header # Header
    5548b745-642b-4b15-8f17-4ce7457689a8: Header # Header
    7242b43a-de73-46de-b5c2-234ba48a8a57: 'Guided Experiences Page' # Guided Experiences Page
    7559fb47-f35b-436d-aceb-300a233317b8: 'Customize Orbits Description' # Customize Orbits Description
    7754bae8-c6eb-4fbe-882b-236621e35f2d: 'Canto DAM' # Canto DAM
    9829e8e1-9862-44ab-902c-90a72e4a81b7: Landing # Landing
    52519e78-2e53-47c5-aa84-c2345d520393: About # About
    547128fa-4529-4483-9968-66425996b69f: EN # EN
    1345707a-2b07-4664-b8d2-25fcb9241212: Content # Content
    9940892d-32f4-4399-acac-ab559ce1c82b: Common # Common
    74319755-d24f-4991-a84a-0c1c031cb21e: 'Asset Link' # Asset Link
    a5b8e4fe-87da-48fc-8156-2a2a973b29e5: URL # URL
    a5bb0742-012f-4683-a471-874944bf3280: Image # Image
    a27ce8af-199a-455d-8d8e-dbeb7b3f117b: About # About
    a61323db-26ac-4898-873c-a6c6b66fcb86: Header # Header
    a1432247-e10b-4c71-b669-23798d01a022: 'Intro Slide' # Intro Slide
    acbea415-ee80-409c-90e2-90ac546820a6: Description # Description
    af1b8590-3d8a-4eb1-90e1-60e3d7407a1a: 'Link text' # Link text
    b49a6e91-b631-4ade-92cc-8c3e3f6db788: 'Customize Orbits Title' # Customize Orbits Title
    b60e78f2-8891-4212-b8c5-4f6fc62b4910: 'Context Information' # Context Information
    b405d3c9-e565-4e57-87eb-6f541ae49070: 'Fun Fact Slide' # Fun Fact Slide
    b882fa04-8a43-4715-a55d-b3344db891bf: 'Table Title' # Table Title
    bdeb1d60-8e9f-44a7-90c3-b928e1545b75: 'Landing Right Button Text' # Landing Right Button Text
    c0bf4db2-5962-4328-abcd-e6a0af1fbfc5: 'Object types' # Object types
    c4ff4a71-a62a-4cb6-b445-6ae6c12381a6: 'Page Content' # Page Content
    c5bc0051-46f3-4ac7-bb8a-a7b808c4b0a7: Thumbnail # Thumbnail
    c5e2a1ff-7d99-4956-8b74-c79601fad6fe: Title # Title
    c9e9db12-fcdb-4b82-a8c8-eef21b3543af: 'Cell Background' # Cell Background
    c44a71b5-f4c8-4209-8433-9878aece9aa5: Text # Text
    c4060079-e438-4c63-8b06-77cdea857fd9: Text # Text
    cb6a7cee-4f9e-4191-8c6d-33ccdd921fec: Text # Text
    cbf3fbbb-2f2b-4568-a228-f8c63ff4601c: 'Row Color' # Row Color
    cc694df6-ebfe-4e0c-b4fe-713761f100df: Text # Text
    cee5c2f8-2801-42c2-a56c-4fe40c85b6f3: 'Site Information' # Site Information
    d3d6215a-2225-4541-b17d-74eb58445af5: 'Default Slide' # Default Slide
    d889713c-632a-4323-bb10-4b2bc53545ad: Asset # Asset
    ddf8dce2-4fa1-43d1-b306-b34d9d97a91b: Content # Content
    dff2a767-333e-4c9d-880c-143e1ca2aaa3: 'Row Content' # Row Content
    e84d2431-7574-44a8-9e23-019823b2dfc3: Default # Default
    e338eebb-6488-4f58-a07e-db43f28ff56b: Image # Image
    e7913600-c914-4ab1-a9bb-abd2bdcbfb94: 'Custom Name' # Custom Name
    ea7cafd8-b2d5-4ffb-b9fb-9a617eef9dfb: Complexity # Complexity
    ec809547-cd72-4016-92f4-e72a89d6620c: Default # Default
    ef474ef1-31d2-45c5-8419-cb15202ba296: 'Guided Experiences Tours' # Guided Experiences Tours
    f1df2c63-97e5-49f0-8f4d-1e704d4945ac: Landing # Landing
    f444667c-6ea1-4e0f-89b2-35b059e27bfc: Link # Link
    fd26bd16-cdc1-44cf-af77-ceb7ecc98e42: Tours # Tours
plugins:
  asset-metadata:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  neo:
    edition: standard
    enabled: true
    licenseKey: ELFLTF1S74Z6RGBQHQNATGU2
    schemaVersion: 2.13.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  universal-dam-integrator:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      appId: $CANTO_APP_ID
      authEndpoint: $CANTO_AUTH_ENDPOINT
      damVolume: cantoDam
      retrieveAssetMetadataEndpoint: $CANTO_ASSET_ENDPOINT
      secretKey: $CANTO_SECRET_KEY
system:
  edition: pro
  live: true
  name: 'Rubin Telescope Education and Public Outreach'
  retryDuration: null
  schemaVersion: 3.7.33
  timeZone: America/Los_Angeles
