dateModified: 1754944808
email:
  fromEmail: $EMAIL_FROM_ADDRESS
  fromName: $EMAIL_SENDER_NAME
  replyToEmail: $EMAIL_REPLY_TO_ADDRESS
  template: $EMAIL_HTML_EMAIL_TEMPLATE
  transportSettings:
    encryptionMethod: tls
    host: $EMAIL_SMTP_HOST_NAME
    password: $EMAIL_SMTP_PASSWORD
    port: $EMAIL_SMTP_PORT
    timeout: '10'
    useAuthentication: '1'
    username: $EMAIL_SMTP_USERNAME
  transportType: craft\mail\transportadapters\Smtp
fs:
  generalImages:
    hasUrls: true
    name: General
    settings:
      bucket: $GCS_GENERAL_BUCKET
      bucketSelectionMode: manual
      expires: '5 minutes'
      keyFileContents: ''
      projectId: $GCP_PROJECT_ID
      subfolder: ''
      visibility: null
    type: craft\googlecloud\Fs
    url: '@assets'
meta:
  __names__:
    00d2f19f-361b-48e1-bcad-9af116c709c2: 'Orbit Viewer' # Orbit Viewer
    1a35bfab-6a39-4c03-b273-2d5e3151c335: 'Rubin Telescope Education and Public Outreach' # Rubin Telescope Education and Public Outreach
    1f8a9fe3-0e8c-4e3f-b6ce-0e1421fe0fbb: 'Landing Center Title' # Landing Center Title
    2c2e1c6a-eb4d-44f1-9a43-8d79b326f354: ES # ES
    2f6b435a-5a6c-4f32-b8b5-4aae301d1738: 'Customize Orbits' # Customize Orbits
    3cbe4fda-03b6-4891-b0ac-892db5b17bb8: Landing # Landing
    3cc93b5a-26a7-43b2-98d9-1d346f30440b: 'flexible - Share Slide - Text' # flexible - Share Slide - Text
    3d8ca907-3314-4e70-8195-610c75f3ef68: 'flexible - Share Slide - Link 4 Text' # flexible - Share Slide - Link 4 Text
    4c6c84cf-d5a1-4d83-a3fa-e1d0276c9ae4: 'Content Blocks' # Content Blocks
    4c977b75-9ee1-4cdb-9d2a-203639f4af84: Links # Links
    4e7f9aec-f2f0-4d0d-bd27-ab2662ab3e08: Duration # Duration
    4e3020e0-9db8-4f8c-8e2e-8884ac2a1a5d: 'flexible - Intro Slide - Content' # flexible - Intro Slide - Content
    4fe339ec-7579-46f4-a362-df6ee8de4b3c: 'Public Schema' # Public Schema
    5d16435b-a18f-4b00-a62e-eb5a38f64561: 'MPC Data Files' # MPC Data Files
    5e48c132-d42b-4192-8aa6-40e239f6889e: 'Data File Quality' # Data File Quality
    5ec16768-675f-4821-9d5c-bdda6be16ddf: 'flexible - Share Slide - Link 2 Text' # flexible - Share Slide - Link 2 Text
    5f0325e0-cdba-4181-a634-bd8ebf451723: 'Entry - Page' # Entry - Page
    06d698cb-d4e4-40cf-ac05-d6d9db0fdc14: 'flexible - Default Slide - Close Up' # flexible - Default Slide - Close Up
    06f925f8-298e-494b-bff7-6fe8024c0859: Frontend # Frontend
    7db205b7-a548-42f1-8c26-416ec51cf3fa: Text # Text
    7fe41358-2add-495c-a748-49a086b55040: Simple # Simple
    8ccd6c1c-8e9b-44e8-93a9-f62589fb4819: 'Default SEO' # Default SEO
    08df75ba-ecc2-470d-84c2-f004b1d30739: Preview # Preview
    8fff3c50-28ba-4af7-8166-e3d82a23ae26: 'SEO Title' # SEO Title
    9ad945a2-a807-403c-aec6-ef28c7849b73: 'Landing Logo' # Landing Logo
    9f3fe24e-520b-44fc-97f5-fa9a2d2622b0: 'flexible - Default Slide - Content' # flexible - Default Slide - Content
    9f7b6402-ce3b-4a99-9180-c0c6c3915642: flexible # flexible
    16e8811b-6d9d-44e1-83b2-16c02e1dcd5a: 'Landing Version' # Landing Version
    20c31add-4c8c-4c9e-a6dc-4ccac3ecfe35: 'flexible - Intro Slide - Title' # flexible - Intro Slide - Title
    29b451f0-26dc-4eae-af12-3041039632b0: Diameter # Diameter
    37b1d17c-d8d5-45f3-9c15-14ef09b62add: 'Tour Picker' # Tour Picker
    39af5de5-d299-4bc5-965a-af2d128c7f1a: 'Alternative Text' # Alternative Text
    45e9d096-0ab6-4324-af5e-61a1be9cff83: 'flexible - Intro Slide - Sub Title' # flexible - Intro Slide - Sub Title
    53d8b6b6-280e-4d4a-adc1-2c3efcb4bd0a: 'Element Category' # Element Category
    59e08766-55d3-4cb0-8b02-b406b1ea45d8: 'Solar system Elements' # Solar system Elements
    96bb1d3d-4098-4112-9dc3-dbffbe908c62: 'Tour Preview' # Tour Preview
    96e2805b-5beb-443c-9ae0-8c03438cc369: 'Help URL' # Help URL
    259c53da-eb2c-4ed5-9688-265402477b30: 'View In Skyviewer Link' # View In Skyviewer Link
    433dd9ce-77cb-4942-8b4d-8e347439bc61: 'flexible - Default Slide - Sub Title' # flexible - Default Slide - Sub Title
    641bcbaa-093a-41bc-a403-6696f52ce6a9: 'Page Type' # Page Type
    907d717b-d9ff-4449-abbf-7c7f5823851b: 'Guided Experiences Page' # Guided Experiences Page
    2817d4b1-3f70-458a-81c2-f82491ce138c: 'Main Color' # Main Color
    3182a473-667d-439f-9cf2-b545be5c23d3: 'Element ID' # Element ID
    3400f929-2ff0-47da-8c15-40bce8b6cebf: 'Customize Orbits' # Customize Orbits
    7242b43a-de73-46de-b5c2-234ba48a8a57: 'Guided Experiences Page' # Guided Experiences Page
    7559fb47-f35b-436d-aceb-300a233317b8: 'Customize Orbits Description' # Customize Orbits Description
    7970cd65-7a96-418a-8581-d6df4e039e6d: 'Plain Text' # Plain Text
    18324a33-d4f9-424d-b03a-c1e74f127122: 'flexible - Share Slide - Link 4' # flexible - Share Slide - Link 4
    52519e78-2e53-47c5-aa84-c2345d520393: About # About
    79574a31-bf11-4c54-a036-bfbb99b93976: 'Object Type Code' # Object Type Code
    294114c2-b0a2-4c1e-971b-f6ab75b78e88: 'SEO Share Image' # SEO Share Image
    510835eb-8d26-4284-abbd-01750b50e6e0: 'flexible - Share Slide - Link 2' # flexible - Share Slide - Link 2
    547128fa-4529-4483-9968-66425996b69f: EN # EN
    1345707a-2b07-4664-b8d2-25fcb9241212: 'flexible - Fun Fact Slide - Content' # flexible - Fun Fact Slide - Content
    19012886-9bc8-45c8-98ca-619268a128d4: 'flexible - Share Slide - Link 1' # flexible - Share Slide - Link 1
    a022545d-8a4f-44cf-adcb-3954b7721751: 'SEO Site Name' # SEO Site Name
    a25b1a87-97c8-4590-ab39-5d2a0e5c214e: 'Main Menu' # Main Menu
    a27ce8af-199a-455d-8d8e-dbeb7b3f117b: About # About
    a320b687-d7a3-4cba-9a9f-f696c52c859c: 'flexible - Share Slide - Link 3' # flexible - Share Slide - Link 3
    a1432247-e10b-4c71-b669-23798d01a022: 'Intro Slide' # Intro Slide
    ac760e25-4731-4206-b6a8-bc36fbf95448: 'flexible - Share Slide - Links Title' # flexible - Share Slide - Links Title
    acbea415-ee80-409c-90e2-90ac546820a6: 'SEO Description' # SEO Description
    ad100cf4-b13d-499b-81ec-170fa9380f19: 'MPC Data Files' # MPC Data Files
    b8a1185f-57c4-4db0-a5c8-fab494cbef2d: 'flexible - Share Slide - Link 3 Text' # flexible - Share Slide - Link 3 Text
    b49a6e91-b631-4ade-92cc-8c3e3f6db788: 'Customize Orbits Title' # Customize Orbits Title
    b60e78f2-8891-4212-b8c5-4f6fc62b4910: 'Context Information' # Context Information
    b405d3c9-e565-4e57-87eb-6f541ae49070: 'Fun Fact Slide' # Fun Fact Slide
    bd7d2ebc-3cf3-4390-b6b5-4e6cc4f1deba: 'How to use URL' # How to use URL
    c0bf4db2-5962-4328-abcd-e6a0af1fbfc5: 'Object types' # Object types
    c4ff4a71-a62a-4cb6-b445-6ae6c12381a6: 'Page Content' # Page Content
    c5bc0051-46f3-4ac7-bb8a-a7b808c4b0a7: 'flexible - Intro Slide - Thumbnail' # flexible - Intro Slide - Thumbnail
    c5e2a1ff-7d99-4956-8b74-c79601fad6fe: 'flexible - Default Slide - Title' # flexible - Default Slide - Title
    c95c837c-b84e-47a5-9903-3c629af16aa8: 'Orbit Viewer' # Orbit Viewer
    ccafd7ca-3768-4e9f-92c6-56ed30825dd3: 'flexible - Share Slide - Link 1 Text' # flexible - Share Slide - Link 1 Text
    d019727b-a6d5-43d9-a688-f10df985a87e: Link # Link
    d3d6215a-2225-4541-b17d-74eb58445af5: 'Default Slide' # Default Slide
    d77e6076-0548-4254-b697-8ffa9980271b: 'flexible - Share Slide - Title' # flexible - Share Slide - Title
    e5d596f6-1cc0-4b55-8c33-2a6dae6aa91d: General # General
    e84d2431-7574-44a8-9e23-019823b2dfc3: Default # Default
    e9726196-f241-49d4-9b6b-9e8d419e6669: 'Link Text' # Link Text
    ea7cafd8-b2d5-4ffb-b9fb-9a617eef9dfb: Complexity # Complexity
    ec809547-cd72-4016-92f4-e72a89d6620c: Default # Default
    ef474ef1-31d2-45c5-8419-cb15202ba296: 'Guided Experiences Tours' # Guided Experiences Tours
    f1df2c63-97e5-49f0-8f4d-1e704d4945ac: Landing # Landing
    fd26bd16-cdc1-44cf-af77-ceb7ecc98e42: Tours # Tours
    fe975ea4-3c59-478a-9c81-221ecbdd3efb: 'Share Slide' # Share Slide
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  google-cloud:
    edition: standard
    enabled: true
    schemaVersion: '2.0'
  neo:
    edition: standard
    enabled: true
    licenseKey: ELFLTF1S74Z6RGBQHQNATGU2
    schemaVersion: 5.1.0.1
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
system:
  edition: pro
  live: true
  name: Orbitviewer
  retryDuration: null
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
