childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: null
field: 4c6c84cf-d5a1-4d83-a3fa-e1d0276c9ae4 # Content Blocks
fieldLayouts:
  2dd1cc59-93d5-4a43-914c-395016509e05:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 7db205b7-a548-42f1-8c26-416ec51cf3fa # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea2e7d54-bdb6-4108-813b-dc1ee114b9c0
            userCondition: null
            warning: null
            width: 100
        name: 'Tab 1'
        uid: f77a57e4-287e-4944-a399-3be89fadde71
        userCondition: null
group: null
groupChildBlockTypes: true
handle: text
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Text
topLevel: true
