childBlocks: null
conditions: null
description: ''
enabled: true
field: 4c6c84cf-d5a1-4d83-a3fa-e1d0276c9ae4 # Content Blocks
fieldLayouts:
  2dd1cc59-93d5-4a43-914c-395016509e05:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7db205b7-a548-42f1-8c26-416ec51cf3fa # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a198dfc-a7b1-472e-9cf1-d31213866ada
            userCondition: null
            warning: null
            width: 100
        name: 'Tab 1'
        uid: 92e5f160-397e-4b13-8bdb-3175cb99653c
        userCondition: null
group: null
groupChildBlockTypes: true
handle: text
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Text
topLevel: true
