fieldLayouts:
  80e92c01-6237-493c-ab12-24da919aca7b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c8d443a3-d398-4528-9def-0a6948745783
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 39af5de5-d299-4bc5-965a-af2d128c7f1a # Alternative Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a179ca6-f4fd-4c8e-b64b-0b3898059ab9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 59ccca1b-05ca-4e88-9191-5bd68292ba24
        userCondition: null
fs: generalImages
handle: generalImages
name: General
sortOrder: 10
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
