fieldLayouts:
  80e92c01-6237-493c-ab12-24da919aca7b:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
          -
            fieldUid: 39af5de5-d299-4bc5-965a-af2d128c7f1a # Alternative Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: generalImages
hasUrls: true
name: General
settings:
  bucket: $GCS_GENERAL_BUCKET
  bucketSelectionMode: manual
  expires: '5 minutes'
  keyFileContents: ''
  projectId: $GCP_PROJECT_ID
  subfolder: ''
sortOrder: 10
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: craft\googlecloud\Volume
url: null
