columnSuffix: null
handle: altText
instructions: 'Required description of the image for non-sighted users (https://webaim.org/techniques/alttext/).'
name: 'Alternative Text'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
