columnSuffix: ogsofuus
contentColumnType: text
fieldGroup: 5b5c2953-79f7-498a-bae7-94a08ec2f8ab # Common Strings
handle: applyFilter
instructions: ''
name: 'Apply Filter'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
