columnSuffix: goienywe
contentColumnType: smallint(1)
fieldGroup: 3c4d26f3-4aa2-48fd-8dd8-400929f9210e # Tours
handle: complexity
instructions: '1 - 5'
name: Complexity
searchable: false
settings:
  decimals: 0
  defaultValue: 1
  max: 5
  min: 1
  prefix: null
  previewCurrency: ''
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
