columnSuffix: goienywe
handle: complexity
instructions: '1 - 5'
name: Complexity
searchable: false
settings:
  decimals: 0
  defaultValue: 1
  max: 5
  min: 1
  prefix: null
  previewCurrency: null
  previewFormat: none
  size: null
  step: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
