columnSuffix: wvpujofd
handle: customizeOrbitsDescription
instructions: null
name: 'Customize Orbits Description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
