columnSuffix: dxiwhrgb
contentColumnType: text
fieldGroup: 3b29031d-3d78-41d3-a340-21abda7bf557 # Customize Your View Panel
handle: customizeTitle
instructions: ''
name: 'Customize Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
