columnSuffix: nqiumkee
contentColumnType: text
fieldGroup: b965ebe0-86b2-4a2e-8cf2-66db5d5f46d0 # DatePicker Tab Texts
handle: datePickerDescription
instructions: ''
name: 'DatePicker Description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
