columnSuffix: mcdivsrn
contentColumnType: integer(10)
fieldGroup: 3c4d26f3-4aa2-48fd-8dd8-400929f9210e # Tours
handle: duration
instructions: ''
name: Duration
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
