columnSuffix: mqwgxifo
contentColumnType: text
fieldGroup: 1655338e-aa59-49ef-ab90-aac2117ecdeb # Share Tab
handle: facebookText
instructions: ''
name: 'Facebook Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
