columnSuffix: null
contentColumnType: string
fieldGroup: 3c4d26f3-4aa2-48fd-8dd8-400929f9210e # Tours
handle: flexible
instructions: ''
name: flexible
searchable: false
settings:
  contentTable: '{{%matrixcontent_flexible}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
