columnSuffix: null
contentColumnType: string
handle: flexible
instructions: null
name: flexible
searchable: false
settings:
  entryTypes:
    -
      uid: d3d6215a-2225-4541-b17d-74eb58445af5
    -
      uid: a1432247-e10b-4c71-b669-23798d01a022
    -
      uid: b405d3c9-e565-4e57-87eb-6f541ae49070
    -
      uid: fe975ea4-3c59-478a-9c81-221ecbdd3efb
  maxEntries: null
  minEntries: 1
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
