columnSuffix: vczrvbad
handle: helpUrl
instructions: null
name: 'Help URL'
searchable: false
settings:
  fullGraphqlData: false
  maxLength: 255
  showLabelField: false
  types:
    - url
translationKeyFormat: null
translationMethod: language
type: craft\fields\Link
