columnSuffix: vczrvbad
contentColumnType: string(255)
handle: helpUrl
instructions: null
name: 'Help URL'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: language
type: craft\fields\Url
