columnSuffix: eoxhumdw
contentColumnType: string(255)
handle: howToUseUrl
instructions: null
name: 'How to use URL'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: language
type: craft\fields\Url
