columnSuffix: cemrxkpa
contentColumnType: text
handle: landingVersion
instructions: null
name: 'Landing Version'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'Version 1.0'
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
