columnSuffix: cemrxkpa
contentColumnType: text
fieldGroup: 9829e8e1-9862-44ab-902c-90a72e4a81b7 # Landing
handle: landingVersion
instructions: ''
name: 'Landing Version'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Version 1.0'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
