columnSuffix: vizqgaaz
contentColumnType: text
handle: landingCenterTitle
instructions: null
name: 'Landing Center Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: '3D orbit viewer'
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
