columnSuffix: null
contentColumnType: string
fieldGroup: 9829e8e1-9862-44ab-902c-90a72e4a81b7 # Landing
handle: landingLogo
instructions: ''
name: 'Landing Logo'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:7754bae8-c6eb-4fbe-882b-236621e35f2d' # Canto DAM
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:7754bae8-c6eb-4fbe-882b-236621e35f2d' # Canto DAM
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
