columnSuffix: null
handle: linkText
instructions: 'Text for optional link at end of block. Will be populated by the page title if left blank and referencing an internal entry.'
name: 'Link Text'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
