columnSuffix: wtnutfkw
handle: mainColor
instructions: null
name: 'Main Color'
searchable: false
settings:
  allowCustomColors: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
