columnSuffix: kxxunrnk
contentColumnType: string
handle: pageType
instructions: 'Defines the type of page: `Standard` for content pages, `Dynamic` for fully API-driven, `Single` for pages defined as the entry type single, `External` for external pages.'
name: 'Page Type'
searchable: true
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - Standard
        -
          - value
          - standard
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Dynamic
        -
          - value
          - dynamic
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Single
        -
          - value
          - single
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - External
        -
          - value
          - external
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
