columnSuffix: johdafaj
contentColumnType: text
fieldGroup: 9940892d-32f4-4399-acac-ab559ce1c82b # Common
handle: pageContent
instructions: null
name: 'Page Content'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
