columnSuffix: null
handle: plainText
instructions: null
name: 'Plain Text'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: Text
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
