columnSuffix: lknesrpg
contentColumnType: text
fieldGroup: fce825cc-0666-4854-9414-90b980363646 # Main Menu
handle: section1Title
instructions: ''
name: 'Section 1 Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
