columnSuffix: null
contentColumnType: text
fieldGroup: cee5c2f8-2801-42c2-a56c-4fe40c85b6f3 # Default SEO
handle: seoDescription
instructions: ''
name: 'SEO Description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
