columnSuffix: ghgyiixf
handle: slideContent
instructions: null
name: 'flexible - Default Slide - Content'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
