columnSuffix: mhcnskqq
handle: subTitle2
instructions: null
name: 'flexible - Intro Slide - Sub Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
