columnSuffix: vayzwtes
handle: thumbnail
instructions: null
name: 'flexible - Intro Slide - Thumbnail'
searchable: false
settings:
  default: false
  offLabel: "Don't use thumbnail"
  onLabel: 'Use thumbnail'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
