columnSuffix: joqugqea
contentColumnType: string(255)
handle: viewInSkyviewerLink
instructions: null
name: 'View In Skyviewer Link'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
