columnSuffix: joqugqea
handle: viewInSkyviewerLink
instructions: null
name: 'View In Skyviewer Link'
searchable: false
settings:
  fullGraphqlData: false
  maxLength: 255
  showLabelField: false
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
