headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Advanced
options:
  alignment:
    options:
      - left
      - right
  fontSize:
    options:
      - tiny
      - small
      - big
      - huge
toolbar:
  - heading
  - '|'
  - underline
  - alignment
  - bold
  - italic
  - link
  - bulletedList
  - numberedList
  - fontSize
  - outdent
  - indent
  - pageBreak
  - fontColor
  - subscript
  - superscript
