defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    handle: default
    uid: ec809547-cd72-4016-92f4-e72a89d6620c # Default
handle: elements
maxAuthors: 1
name: 'Solar system Elements'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2c2e1c6a-eb4d-44f1-9a43-8d79b326f354: # ES
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  547128fa-4529-4483-9968-66425996b69f: # EN
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
