defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 7242b43a-de73-46de-b5c2-234ba48a8a57 # Guided Experiences Page
handle: guidedExperiences
maxAuthors: 1
name: 'Guided Experiences Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  2c2e1c6a-eb4d-44f1-9a43-8d79b326f354: # ES
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  547128fa-4529-4483-9968-66425996b69f: # EN
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
