defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: beb4775c-f7bf-42c7-913d-59d167a09341 # How to Use
handle: howToUse
maxAuthors: 1
name: 'How to Use'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'How to Use'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2c2e1c6a-eb4d-44f1-9a43-8d79b326f354: # ES
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: how-to-use
  547128fa-4529-4483-9968-66425996b69f: # EN
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: how-to-use
type: single
