defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c95c837c-b84e-47a5-9903-3c629af16aa8 # Orbit Viewer
handle: orbitViewer
maxAuthors: 1
name: 'Orbit Viewer'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2c2e1c6a-eb4d-44f1-9a43-8d79b326f354: # ES
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  547128fa-4529-4483-9968-66425996b69f: # EN
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
