childBlocks: ''
field: 4c6c84cf-d5a1-4d83-a3fa-e1d0276c9ae4 # Content Blocks
fieldLayouts:
  2dd1cc59-93d5-4a43-914c-395016509e05:
    tabs:
      -
        elements:
          -
            fieldUid: 7db205b7-a548-42f1-8c26-416ec51cf3fa # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tab 1'
        sortOrder: 1
handle: text
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Text
sortOrder: 1
topLevel: true
